name: CeramoStone Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Скачиваем код репозитория
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Запускаем автотест
        run: python test1.py

